"""District code → name mapping from USSC codebook."""
DISTRICT_MAP = {
    1: "D.C.", 2: "Maine", 3: "Massachusetts", 4: "New Hampshire",
    5: "Puerto Rico", 6: "Rhode Island", 7: "Connecticut",
    8: "E.D. New York", 9: "N.D. New York", 10: "S.D. New York",
    11: "W.D. New York", 12: "Vermont", 14: "New Jersey",
    15: "E.D. Pennsylvania", 16: "M.D. Pennsylvania", 17: "W.D. Pennsylvania",
    18: "Virgin Islands", 19: "Maryland",
    20: "E.D. North Carolina", 21: "M.D. North Carolina", 22: "W.D. North Carolina",
    23: "South Carolina", 24: "E.D. Virginia", 25: "W.D. Virginia",
    26: "N.D. West Virginia", 27: "S.D. West Virginia",
    28: "E.D. Louisiana", 29: "M.D. Louisiana", 30: "W.D. Louisiana",
    31: "N.D. Mississippi", 32: "S.D. Mississippi",
    33: "E.D. Texas", 34: "N.D. Texas", 35: "S.D. Texas", 36: "W.D. Texas",
    37: "E.D. Kentucky", 38: "W.D. Kentucky",
    39: "E.D. Michigan", 40: "W.D. Michigan",
    41: "N.D. Ohio", 42: "S.D. Ohio",
    43: "E.D. Tennessee", 44: "M.D. Tennessee", 45: "W.D. Tennessee",
    46: "C.D. Illinois", 47: "N.D. Illinois", 48: "S.D. Illinois",
    49: "N.D. Indiana", 50: "S.D. Indiana",
    51: "E.D. Wisconsin", 52: "W.D. Wisconsin",
    53: "E.D. Arkansas", 54: "W.D. Arkansas",
    55: "N.D. Iowa", 56: "S.D. Iowa", 57: "Minnesota",
    58: "E.D. Missouri", 59: "W.D. Missouri", 60: "Nebraska",
    61: "North Dakota", 62: "South Dakota",
    63: "Alaska", 64: "Arizona",
    65: "C.D. California", 66: "E.D. California",
    67: "N.D. California", 68: "S.D. California",
    69: "Guam", 70: "Hawaii", 71: "Idaho", 72: "Montana",
    73: "Nevada", 75: "Oregon",
    76: "E.D. Washington", 77: "W.D. Washington",
    78: "Colorado", 79: "Kansas", 80: "New Mexico",
    81: "E.D. Oklahoma", 82: "N.D. Oklahoma", 83: "W.D. Oklahoma",
    84: "Utah", 85: "Wyoming",
    86: "M.D. Alabama", 87: "N.D. Alabama", 88: "S.D. Alabama",
    89: "M.D. Florida", 90: "N.D. Florida", 91: "S.D. Florida",
    92: "M.D. Georgia", 93: "N.D. Georgia", 94: "S.D. Georgia",
}
